server:
  port: 8888
spring:
  application: 
    name: cloud-config-server
  cloud:
    config:
      server:
        git:
#          uri: /mnt/work/LinuxEnv/STSWorkspace/cloud-config-files
          uri: E:\\WinEnv\\intellijWS\\CostTrackerWS\\cloud-config-files
          refreshRate: 0